title: Cut
short_title: cut.social
description: "Cut: Design Experiments"
baseurl: ""
url: ""
theme: minima
minima:
  skin: dark
show_excerpts: true
header_pages:
  - index.md
  - demo.md
  - blog.md
  - about.md
  - cv.md
collections:
  - members
plugins:
  - jekyll-pdf-embed
twitter_username: salarrad

