title: Cut the Cake
short_title: cut.social
description: "Cut The Cake: Design and Publish Social Experiments"
baseurl: ""
url: ""
theme: minima
minima:
  skin: dark
show_excerpts: true
header_pages:
  - index.md
  - demo.md
  - blog.md
  - about.md
  - cv.md
collections:
  - members
