title: Cut the Cake
short_title: Cut the Cake
description: "Cut The Cake: Design and Publish Social Experiments"
baseurl: ""
url: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
navs:
  - title: "About"
    url: "https://blog.cut.social/about"
  - title: "Blog"
    url: "https://blog.cut.social"
  - title: "Case Studies"
    url: "https://beta.cut.social/designer/dashboard"
  - title: "Contact"
    url: "https://cut.social/contact"

# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-feed
  - jekyll-archives
