title: Cut The Cake
short_title: Cut The Cake
description: "Cut The Cake: Design and Publish Social Experiments"
baseurl: blog.cut.social
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
gems:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
